import "./globals.css";

import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>

        <div className="main_container">
          <Navbar />
          <div className="main_content">
            {children}
          </div>
        </div>


      </body>
    </html>
  );
}
